In [1]:
#Numpy vs Python lists- Performance test
#Example 1: Adding Two Lists vs. Numpy Arrays

import numpy as np
import time

#Python list
size= 1_000_00
list1= list(range(size))
list2= list(range(size))

start= time.time()
result= [x+y for x, y in zip(list1, list2)]
end= time.time()

print("Python list addition time:", end- start)

#Numpy Array
arr1= np.array(list1)
arr2= np.array(list2)

start= time.time()
result= arr1+ arr2  #Vectorized operation
end= time.time()
print("NumPy array addition time:", end- start)

Python list addition time: 0.01193380355834961
NumPy array addition time: 0.004202127456665039


In [2]:
#Creating numpy arrays
import numpy as np

#creating a 1d numpy array
arr1= np.array([1, 2, 3, 4, 5])
print(arr1)

#creating a 2d numpy array
arr2= np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

#checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


In [3]:
#Memory efficiency- Numpy vs. Lists

import sys

list_data= list(range(1000))
numpy_data= np.array(list_data)

print("Python list size:", sys.getsizeof(list_data)* len(list_data), "bytes")
print("Numpy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
Numpy array size: 8000 bytes


In [4]:
#Vectorization- No more Loops!
#Example: Squaring Elements

#Python list(loop based)
list_squares= [x**2 for x in list1]

#numpy(vectorized)
numpy_squares= arr1** 2